export const MODAL_BROWSE = "MODAL_BROWSE";
export const MODAL_LOGIN = "MODAL_LOGIN";
export const MODAL_ITINERARY_CREATE = "MODAL_ITINERARY_CREATE";
export const MODAL_STORY_CREATE = "MODAL_STORY_CREATE";
