#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "master" ]; then
  echo "
  ##Branch protection rules##

    * master branch에 직접 commit 하지 않습니다.
"
  exit 1
fi